services:
  db:
    image: postgres:16
    container_name: alitas_db
    environment:
      POSTGRES_USER: alitas
      POSTGRES_PASSWORD: alitas123
      POSTGRES_DB: alitas_bonnibel
    ports:
      - "5432:5432"
    volumes:
      - alitas_pgdata:/var/lib/postgresql/data

volumes:
  alitas_pgdata:
